<a href="https://colab.research.google.com/github/Aishwaryamishra01/C-Language-projects/blob/main/neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

neuraon is the basic unit of the neural network or we can say that is the smallest neural neetwork

In [12]:
import torch
import torch.nn as nn #iske andar basically hamare building blocks hote hai jaise ki hame koi activation function cuse karna hai layers create karni hai
# // this is tha alias that we have




In [13]:
# creation of input
torch.manual_seed(42) # controlling the randomness
inputs = torch.tensor([1.0,2.0 , 3.0]) #input hame float main dena hota hai

#  tesor creates multidimentional array




In [14]:
#creating a neuron

neuron = nn.Linear(in_features = 3 , out_features = 1 ) # defining the number of input and numbere of output for the neuron


In [15]:
#storing the output of the neuron

output = neuron(inputs);
#  printing the output
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [16]:
#bias
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

weighted sum formula = $$ ∑_{i=1} ^{n} x_i. w_i + bias$$


In [17]:
#varifying the output using weighted sum formula
#we use @ for dot product in python
neuron.weight @inputs +neuron.bias


tensor([1.5244], grad_fn=<AddBackward0>)